### ISSUE TITLE
enhancement: refresh QR code every 15 seconds

### ISSUE THREAD

**Issue by SJang1** [kiding/kakao-qr-api#3]
QR code expires every 15 seconds, so somehow we need to refresh QR code every 15 seconds.
First 15 seconds is not enough to scan code, that's why it need to be refreshed.

**Comment by kiding** [comment]
QR 데이터는 Lambda에 저장해두지 않으며, 요청을 받을 때마다 카카오 서버에 요청하여 새로운 QR 데이터를 수신합니다. 15초마다 새로운 값을 요청해서 어딘가로 콜백해 주는 Webhook 기능을 만들 수는 있겠지만... 카카오 서버에 반드시 부담이 되기 때문에 (= 막힐 소지가 있어서...) 다소 지양했으면 좋겠다는 생각입니다.

**Comment by Hoto-Cocoa** [comment]
이 API 자체는 GET 요청이 날아오면 QR 원문만 제공해주는 API니까 15초마다 갱신을 시키는건 QR 코드를 만드는 단에서 해야 할 것 같습니다. 만료 시간을 포함시킨다던가 하는 몇가지 방법이 생각나긴 하는데 지금과 같이 GET을 보내면 QR 원문이 그대로 내려오는 것보단 아무래도 사용하기 귀찮아지지 않나 싶네요.
